
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\3.Extractor\E_01.qvw"
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\3.Extractor\E_02.qvw"
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\5.Transform\T_01.qvw"
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\5.Transform\T_02.qvw"
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\5.Transform\T_03.qvw"
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\5.Transform\T_04.qvw"
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\5.Transform\T_05.qvw"
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\5.Transform\T_06.qvw"
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\5.Transform\T_07.qvw"
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\7.DataModel\Model_Projeto_Iron.qvw"
"C:\Program Files\QlikView\Qv.exe" /r "C:\Apps Internas\Projeto Iron - Desenv\Qlik_v2\8.APP\Projeto_Iron.qvw"
